name : build
on: [push]
jobs:
  buildAnalyzer:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.3
        with:
          python-version: 3.11
          auto-activate-base: false
      - name: Run setup.sh
        run: |
          source setup.sh
          
